### ISSUE TITLE
Meteor.users.findOne() can be an expensive db operation

### ISSUE THREAD

**Issue by wildhart** [Meteor-Community-Packages/meteor-partitioner#32]
In `grouping.coffee` I suggest changing the line:
```
user = Meteor.users.findOne(userId})
```
to
```
user = Meteor.users.findOne(userId, {fields: groupId: 1, admin: 1})
```
so that the entire user object is not fetched from the database server.  Applications may store significant amounts of extra data on the user object.

**Comment by wildhart** [comment]
Also here:
```
  return true unless Meteor.user()?.admin
```
should be:
```
  return true unless Meteor.user({admin: 1})?.admin
```

**Comment by mizzao** [comment]
Sure. If you make a PR I will merge it.

**Comment by hzwzw** [comment]
@mizzao 
I make a PR #34 , Please check.
